version: "3"
services:
  gitlab:
    image: gitlab-pi:dev
    privileged: true
    restart: unless-stopped
    hostname: "kube4"
    networks:
      - gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL}'
    ports:
      - "8080:80"
      - "8443:443"
      - "2222:22"
    volumes:
      - ${GITLAB_HOME}/config:/etc/gitlab
      - ${GITLAB_HOME}/logs:/var/log/gitlab
      - ${GITLAB_HOME}/data:/var/opt/gitlab

networks:
  gitlab:
